
/* --- team members --- */

var newstack = document.getElementById('aside-add-member-btn');
// expand new members popup
newstack.addEventListener('click', CreatenewContent );
// get generated tokens when expanding new members popup
newstack.addEventListener('click', GetAllTokens);

// get all tokens generated by workspace
function GetAllTokens() {

    var appendTo = document.getElementById('member-tokens-assigned');
    var space = document.querySelector('body').getAttribute('body_data_id');

    axios.get('/0/workspace/'+ space + '/getAllTokens').then(function ( res ) {

        var tokens = res.data;

        console.log(tokens);

        tokens.forEach(function( generated, index) {
              var html = document.createElement('div');
              html.classList.add('token-generated');

              generated.claimed ? html.classList.add('token-used') : html.classList.add('token-free');
              html.innerHTML = '<p>' + generated.token  + '</p>';

              appendTo.appendChild(html);
        });
    })
    .catch(function (error) {  console.log(error) });
}

// generate a single token on clicking generate token btn
function generateToken( el ) {

      var space = document.querySelector('body').getAttribute('body_data_id');

      axios.get('/0/workspace/'+ space + '/genToken').then(function ( res ) {

            var generated = res.data;

            // add new key to content
            var appendTo = document.getElementById('member-tokens-assigned');

            var html = document.createElement('div');
            html.classList.add('token-generated');

            generated.claimed ? html.classList.add('token-used') : html.classList.add('token-free');
            html.innerHTML = '<p>' + generated.token  + '</p>';

            appendTo.appendChild(html);
      })
      .catch(function (error) { console.log(error); });
}
